@ stdcall DnsFreeProxyName(wstr)
@ stdcall DnsIsZtEnabled()
@ stdcall DnsGetProxyInformation(wstr ptr ptr ptr ptr)
@ stdcall DnsQueryEx(ptr ptr ptr)
@ stdcall DnsServiceBrowse(ptr ptr)
@ stdcall DnsServiceBrowseCancel(ptr)