1 stdcall DllCanUnloadNow() 
2 stdcall DllGetClassObject(ptr ptr ptr)
3 stdcall DllRegisterServer()
4 stdcall DllUnregisterServer()
5 stdcall SvchostPushServiceGlobals(ptr)
6 stdcall WinHttpAddRequestHeaders(ptr wstr long long)
7 stdcall WinHttpAutoProxySvcMain(long wstr)
8 stdcall WinHttpCheckPlatform()
9 stdcall WinHttpCloseHandle(ptr)
10 stdcall WinHttpConnect(ptr wstr long long)
11 stdcall WinHttpCrackUrl(wstr long long ptr)
12 stdcall WinHttpCreateUrl(ptr long ptr ptr)
13 stdcall WinHttpDetectAutoProxyConfigUrl(long ptr)
14 stdcall WinHttpGetDefaultProxyConfiguration(ptr)
15 stdcall WinHttpGetIEProxyConfigForCurrentUser(ptr)
16 stdcall WinHttpGetProxyForUrl(ptr wstr ptr ptr)
17 stdcall WinHttpOpen(wstr long wstr wstr long)
18 stdcall WinHttpOpenRequest(ptr wstr wstr wstr wstr ptr long)
19 stdcall WinHttpQueryAuthSchemes(ptr ptr ptr ptr)
20 stdcall WinHttpQueryDataAvailable(ptr ptr)
21 stdcall WinHttpQueryHeaders(ptr long wstr ptr ptr ptr)
22 stdcall WinHttpQueryOption(ptr long ptr ptr)
23 stdcall WinHttpReadData(ptr ptr long ptr)
24 stdcall WinHttpReceiveResponse(ptr ptr)
25 stdcall WinHttpSendRequest(ptr wstr long ptr long long long)
26 stdcall WinHttpSetCredentials(ptr long long wstr ptr ptr)
27 stdcall WinHttpSetDefaultProxyConfiguration(ptr)
28 stdcall WinHttpSetOption(ptr long ptr long)
29 stdcall WinHttpSetStatusCallback(ptr ptr long long)
30 stdcall WinHttpSetTimeouts(ptr long long long long)
31 stdcall WinHttpTimeFromSystemTime(ptr ptr)
32 stdcall WinHttpTimeToSystemTime(wstr ptr)
33 stdcall WinHttpWriteData(ptr ptr long ptr)

#Win8 functions
@ stdcall WinHttpCreateProxyResolver(ptr ptr)
@ stdcall WinHttpFreeProxyResult(ptr)
@ stdcall WinHttpGetProxyForUrlEx(ptr wstr ptr ptr)
@ stdcall WinHttpGetProxyResult(ptr ptr)
@ stdcall WinHttpWebSocketCompleteUpgrade(ptr ptr)
@ stdcall WinHttpWebSocketClose(ptr long ptr long)
@ stdcall WinHttpWebSocketReceive(ptr ptr long ptr ptr)
@ stdcall WinHttpWebSocketSend(ptr long ptr long)
@ stdcall WinHttpWebSocketShutdown(ptr long ptr long)