1 stdcall D2D1CreateFactory(long ptr ptr ptr)
2 stdcall D2D1MakeRotateMatrix(float float float ptr)
3 stdcall D2D1MakeSkewMatrix(float float float float ptr)
4 stdcall D2D1IsMatrixInvertible(ptr)
5 stdcall D2D1InvertMatrix(ptr)
6 stdcall D2D1ConvertColorSpace(long long ptr)
7 stdcall D2D1CreateDevice(ptr ptr ptr)
8 stdcall D2D1CreateDeviceContext(ptr ptr ptr)
9 stdcall D2D1SinCos(float ptr ptr)
10 stdcall D2D1Tan(float)
11 stdcall D2D1Vec3Length(float float float)
12 stdcall D2D1ComputeMaximumScaleFactor(ptr)